### ISSUE TITLE
Not compatible with Jersey 2.26-b06

### ISSUE THREAD

**Issue by huangliang10987** [silb/shiro-jersey#11]
Hi silb,

I found that after upgrading Jersey from 2.25.1 to 2.26-b06, the interface ValueFactoryProvider is removed from the jar of Jersey. This cause an issue with this lib. 

Thanks

**Comment by ThomasCraigNelson** [comment]
Hi slib, I need this, so I'm going to attempt a variation leading to a pull request, any would you be willing to engage in email correspondence on this?  Thanks.

**Comment by silb** [comment]
Please note that Jersey 2.26 hasn't been released yet and comes with no compatibility promises , see <https://jersey.github.io/download.html>. And the link from the download page to the 2.26 changelog is broken. So I'm not too eager on chasing 2.26 compatibility quite yet.

Maybe shiro-jersey is compatible if you only use the declarative annotations and not the injection part? That is, remove registration of `AuthInjectionBinder` and `SubjectFactory` from the application initialization, but keep `AuthorizationFilterFeature`. You can still fetch the `Subject` from `SecurityUtils`. 

The Shiro project is implementing annotation support but no filtering in their Shiro module, see [SHIRO-392](https://issues.apache.org/jira/browse/SHIRO-392).

**Comment by ThomasCraigNelson** [comment]
Thanks Stig for your response.  I decided to use 2.25.1 rather than wrestle
with this at this time.

Regards,
Tom

**Comment by boris-petrov** [comment]
Jersey 2.26 is out with a changelog and everything. The same problem still occurs.

@silb - should I wait on some fixes on `shiro-jersey's` side or should I try some workaround or something else?

**Comment by silb** [comment]
Don't expect a fix anytime soon. The injection parts of Shiro Jersey need to be rewritten for Jersey 2.26. The Jersey 1.x to 2.x transition took a lot of wrestling with the HK2 injection API. Now it must be done again for the new injection API in Jersey 2.26.

**Comment by boris-petrov** [comment]
I'm not sure there is a new injection API. I think they just extracted it in a different JAR but haven't changed it - but that's for you to say.

So what do you suggest we do? Remove most of the usages of shiro-jersey and wait for a new version? That's would be a pity.

**Comment by silb** [comment]
I suggest you use the workaround I have suggested in this thread.

**Comment by silb** [comment]
Jersey 2.26 is still using HK2 for injection through the Maven dependency `org.glassfish.jersey.inject:jersey-hk2:2.26` mentioned in the [release notes](https://jersey.github.io/release-notes/2.26.html), but the HK2 version got bumped from 2.4 to 2.5, thus breaking the injection API.

**Comment by silb** [comment]
There is progress in the branch [jersey-2.26](https://github.com/silb/shiro-jersey/tree/jersey-2.26).

**Comment by boris-petrov** [comment]
@silb - is there any progress on this? :)

**Comment by silb** [comment]
The code in the branch jersey-2.26 is ready as far as I know, but I haven't tested it in any real application. Could you test the code in the branch in your application?

I find the injection APIs for Jersey difficult to understand, so I could have introduced errors.

**Comment by boris-petrov** [comment]
OK, I'm trying it however now that the `AuthInjectionBinder` is removed, how are `@Auth` annotations supposed to work? They don't work in my case now... am I missing something?

**Comment by silb** [comment]
Did you follow the [migration instructions](https://github.com/silb/shiro-jersey/tree/jersey-2.26#migrating-from-02x)?

**Comment by boris-petrov** [comment]
Yes, as I mentioned in the comment above, I removed `AuthInjectionBinder` and everything compiles fine, however variables that I've marked as `@Auth` are `null` at runtime. What should I do? Is `@Auth` also "deprecated" and should not be used?

**Comment by silb** [comment]
The intention is that method parameter injection using `@Auth` should be backwards compatible. Do your code inject into method parameters or fields?

**Comment by silb** [comment]
Can you retrieve the Shiro `Subject` using `SecurityUtils.getSubject`?

**Comment by boris-petrov** [comment]
I use `@Auth` for fields - using it as method parameters is kind of pointless because I could use `SecurityUtils.getSubject` in the method instead (which I am doing right now as a workaround and it works fine). Are you saying that `@Auth` is not supposed to work on fields? Is that something that can be fixed?

**Comment by silb** [comment]
Field injection is not supported. It was never supported in the 0.1 and 0.2 releases either.

**Comment by boris-petrov** [comment]
Oh, OK, that was working totally fine before. Never knew it was unsupported. Is there a technical reason for that or it's just unimplemented?

**Comment by silb** [comment]
Mainly to avoid maintaining two injections mechanisms using the HK2 APIs.

**Comment by boris-petrov** [comment]
I see. In that case I guess this issue here could be closed if you merge the branch into master (although for my case specifically nothing will change - as the previous version works also fine) and I could create a new one for the field injection for you to try to implement at some point in the future when you have the time.

**Comment by stiancognite** [comment]
I just gave 0.3.0-SNAPSHOT a shot. I removed `AuthInjectionBinder` and things compile, but in tests I'm seeing a lot of `java.lang.NoClassDefFoundError: org/glassfish/jersey/server/spi/internal/ValueParamProvider`.

Stacktrace:
```
java.lang.NoClassDefFoundError: org/glassfish/jersey/server/spi/internal/ValueParamProvider

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ...
```

Before I dive deeper into it: Any chance one of you know what I have to do here?

**Comment by boris-petrov** [comment]
This seems very familiar but I have forgotten the reason. I am using 0.2.0 by the way, with Jersey 2.26. It works just fine.

**Comment by stiancognite** [comment]
Thank you for the quick reply!:) I thought I had to use `0.3.0-SNAPSHOT` to get past an error, but that wasn't the case.

**Comment by tuanng-cognite** [comment]
is there any plan for releasing 0.3.0?

**Comment by silb** [comment]
Yes, when I am confident that the injection part in the branch jersey-2.26 is releasable.

Could you test the injection functionality in the branch jersey-2.26 using Jersey 2.26+?

**Comment by egore** [comment]
Successfully tested in a production app with jersey 2.27 and shiro-jersey 0.3.0-SNAPSHOT.

**Comment by ahlesunnatwaljammat** [comment]
@silb where can i find the shiro-jersey 0.3.0-SNAPSHOT maven??

**Comment by Xaerxess** [comment]
Hi @silb, any plans of releasing 0.3.0 (and shiro-dropwizard, too, because [dropwizard-2.0 has just came out](https://github.com/dropwizard/dropwizard/releases/tag/v2.0.0) and it uses Jersey 2.29.1)? Do you need any help?
